# Generated by Django 3.1.5 on 2021-02-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='pro_precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
