# Generated by Django 3.1.5 on 2021-02-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0002_auto_20210201_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(max_length=255)),
                ('cat_itbms', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
