# Generated by Django 3.1.5 on 2021-02-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0004_productos_pro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='pro_imagen',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
