# Generated by Django 3.1.5 on 2021-02-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0005_productos_pro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='pro_imagen',
            field=models.ImageField(null=True, upload_to='FUNDASTORE\\STATIC\\productos'),
        ),
    ]
