# Generated by Django 3.1.5 on 2021-02-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0006_auto_20210208_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='pro_descripcion',
            field=models.TextField(null=True),
        ),
    ]
