# Generated by Django 3.1.5 on 2021-02-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0010_auto_20210208_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='pro_imagen',
        ),
    ]
