# Generated by Django 3.1.5 on 2021-02-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0011_remove_productos_pro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='pro_imagen',
            field=models.ImageField(default='default.png', max_length=255, upload_to='PRODUCTO'),
        ),
    ]
