# Generated by Django 3.1.5 on 2021-02-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0012_productos_pro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='pro_imagen',
            field=models.ImageField(blank=True, default='default.png', max_length=255, upload_to='PRODUCTO'),
        ),
    ]
