# Generated by Django 3.1.5 on 2021-02-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0013_auto_20210208_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='pro_moneda',
            field=models.CharField(choices=[('USD', 'DÓLAR ESTADOUNIDENSE'), ('EUR', 'EURO EUROPEO'), ('PAB', 'BALBOA PANAMEÑO')], default='USD', max_length=3),
        ),
    ]
