# Generated by Django 3.1.5 on 2021-02-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCTOS', '0014_productos_pro_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='pro_moneda',
            field=models.CharField(choices=[('USD', 'DÓLAR ESTADOUNIDENSE'), ('EUR', 'EURO'), ('PAB', 'BALBOA PANAMEÑO')], default='USD', max_length=3),
        ),
    ]
