# Generated by Django 3.1.5 on 2021-02-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRINCIPAL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blg_mini',
            field=models.ImageField(max_length=255, null=True, upload_to='blog/banners'),
        ),
    ]
