# Generated by Django 3.1.5 on 2021-02-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRINCIPAL', '0002_blog_blg_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blg_descripcion',
            field=models.TextField(default='Algo de texto aqui'),
        ),
    ]
